android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official
systemProp.user.language=en
systemProp.user.country=US
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
org.gradle.jvmargs=-Xmx1400m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.workers.max=1
org.gradle.daemon=false
